name: Update M3U Playlist

on:
  schedule:
    - cron: '*/30 * * * *'   # chạy mỗi 30 phút
  workflow_dispatch:         # cho phép chạy tay

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run script
        run: |
          python bongda.py   # ⚠️ đổi đúng tên file nếu khác

      - name: Commit & Push if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add tv.m3u full.m3u

          git diff --cached --quiet || git commit -m "Auto update m3u"

          git push
